spring.application.name=docshelper
# 1. Konfiguracja Ollama (LLM + Embeddings)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.1:8b
spring.ai.ollama.embedding.options.model=bge-m3
# 2. Połączenie z PostgreSQL z kontenera Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/docshelper_db
spring.datasource.username=docsuser
spring.datasource.password=docspassword
spring.datasource.driver-class-name=org.postgresql.Driver
# 3. Konfiguracja Bazy Wektorowej (pgvector)
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
# Ważne: bge-m3 wypluwa wektory o wymiarze 1024!
spring.ai.vectorstore.pgvector.dimensions=1024
# 4. Konfiguracja Spring Data Jpa
spring.jpa.hibernate.ddl-auto=update